#!/bin/bash
drawTitle()
{
echo "=========================================="
echo "=== GIT PUSH AUTOMATED SCRIPT FOR MILD ==="
echo "=========================================="
}
waitSec()
{
echo -ne "Waiting 3 seconds..."\\r
sleep 1
echo -ne "Waiting 2 seconds..."\\r
sleep 1
echo -ne "Waiting 1 second..."\\r
sleep 1
}
clear
drawTitle
echo "This script will automatically pull any"
echo "changes from the repo before pushing your"
echo "changes."
echo "=========================================="
waitSec
clear
drawTitle
echo "Pulling any changes from repo."
git pull
waitSec
clear
drawTitle
echo "Preparing to push changes."
git add -u
git add *
echo -e "Enter a commit message:"
read commitmessage
echo "=========================================="
git commit -m "$commitmessage"
echo -e "Comitting  with the message:"
echo $commitmessage
echo "=========================================="
echo "Pushing to origin master."
echo "========================================="
echo "You will need your Github credentials to"
echo "continue."
echo "========================================="
git push origin master
echo "=========================================="
echo "Your changes have been pushed to the"
echo "origin master branch. Any errors should"
echo "be shown above."
echo "=========================================="
